// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6hLxH5I7ySpQHVMRtRF5CCWdXdTLOoNY',
    appId: '1:912799447558:web:b1ace8a51c304f91fd6187',
    messagingSenderId: '912799447558',
    projectId: 'magam-5f033',
    authDomain: 'magam-5f033.firebaseapp.com',
    storageBucket: 'magam-5f033.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqgzfvv6qcRLVMOH5R87uHrjs3X4gnWxQ',
    appId: '1:912799447558:android:354b9522f79877d4fd6187',
    messagingSenderId: '912799447558',
    projectId: 'magam-5f033',
    storageBucket: 'magam-5f033.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf1dfC_fxonFa4y0o8e-7u03bt4fBsa3E',
    appId: '1:912799447558:ios:dfefd8d63966fdfffd6187',
    messagingSenderId: '912799447558',
    projectId: 'magam-5f033',
    storageBucket: 'magam-5f033.firebasestorage.app',
    iosBundleId: 'com.company.magam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf1dfC_fxonFa4y0o8e-7u03bt4fBsa3E',
    appId: '1:912799447558:ios:5a0685c0c56788f6fd6187',
    messagingSenderId: '912799447558',
    projectId: 'magam-5f033',
    storageBucket: 'magam-5f033.firebasestorage.app',
    iosBundleId: 'com.example.magam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6hLxH5I7ySpQHVMRtRF5CCWdXdTLOoNY',
    appId: '1:912799447558:web:ab71fd1fefb9d2fbfd6187',
    messagingSenderId: '912799447558',
    projectId: 'magam-5f033',
    authDomain: 'magam-5f033.firebaseapp.com',
    storageBucket: 'magam-5f033.firebasestorage.app',
  );
}
